# Generated by Django 3.1.3 on 2020-12-03 19:01

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import expertApp.models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('expertId', models.CharField(default=expertApp.models.randomidgenerator, editable=False, max_length=25, primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(default='', max_length=300)),
                ('email', models.EmailField(default='', max_length=50)),
                ('yearsInterviewedFor', models.CharField(choices=[('', 'Interviewing Experience'), ('lessThanOne', 'Less than 1 year'), ('oneToThree', '1 - 3 years'), ('threeToFive', '3 - 5 years'), ('fiveToTen', '5 - 10 years'), ('moreThanTen', 'More than 10 years')], default='', max_length=12)),
                ('lastname', models.CharField(default='', max_length=300)),
                ('phoneNumber', phone_field.models.PhoneField(default='', help_text='Contact phone number', max_length=31)),
                ('image', models.ImageField(default='./mockWizProject/static/images/default.png', upload_to='expert/profile')),
                ('jobTitle', models.CharField(blank=True, default='', max_length=100)),
                ('organization', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('linkedInUrl', models.URLField(default='', max_length=400)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('49.00'), max_digits=6, null=True)),
                ('charityName', models.CharField(default='', max_length=300, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('noOfBookings', models.IntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('approved', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=1, null=True)),
                ('published', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=1)),
                ('starKey', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=1)),
                ('expertiseFunction', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pagesApp.function')),
            ],
        ),
    ]
